#if !defined(clox_vm_h)
#define clox_vm_h

#include "chunk.h"

#define STACK_MAX 256

/**
 * struct vm - structure to hold the vm's internal state.
 * @chunk: pointer to the chunk the vm executes.
 * @ip: pointer to the location of the currently executing instruction.
 * @stack: keeps track of the temporary values generated by an expression.
*/
typedef struct virtualMachine
{
	Chunk* chunk;
	u_int8_t* ip;
	Value stack[STACK_MAX];
	Value* stackTop;
} VM;

/**
 * enum status - enumerates the possible outcomes of for the
 * virtual machine.
 * @INTERPRET_OK: no issues occurred.
 * @INTREPRET_COMPILE_ERROR: a compile time error occurred.
 * @INTREPRET_RUNTIME_ERROR: a runtime error occurred.
*/
typedef enum status
{
	INTERPRET_OK,
	INTERPRET_COMPILE_ERROR,
	INTERPRET_RUNTIME_ERROR
} InterpretResult;

void initVM();
void freeVM();
InterpretResult interpret(Chunk* chunk);
// stack protocol supports these two operations.
void push(Value value);
Value pop();

#endif // clox_vm_h
